name: Release
run-name: Release ${{ github.ref_name }}

on:
  workflow_dispatch:
  release:
    types:
      - published

env:
  RELEASE_TAG: ${{ github.event.release.tag_name || github.ref_name }}

jobs:
  release-nuget:
    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.100

      - name: Download GitHub release artifacts
        uses: robinraju/release-downloader@v1.11
        with:
          tag: ${{ env.RELEASE_TAG }}
          fileName: '*.nupkg'

      - name: Push packages to NuGet
        run: |
          shopt -s nullglob
          for pkg in ./*.nupkg; do
            dotnet nuget push "$pkg" --skip-duplicate --api-key "${{ secrets.NUGET_KEY }}" --source https://api.nuget.org/v3/index.json
          done
